Createページ作成
if-mentor/next_todo_11 pull request #7
Opened 2023-08-19 12:54 UTC by Mi462

### 実施したこと
CreateページのUI実装

2023-08-20 11:30 UTC, shtk0119 requested changes
コメントしたものの修正をお願いします。

2023-08-20 11:30 UTC, shtk0119 commented on app/create/page.tsx
> +
この改行は消してください。

2023-08-20 11:30 UTC, shtk0119 commented on app/create/page.tsx
> +
改行を消してください。

2023-08-26 13:57 UTC, Mi462 commented on app/create/page.tsx
> +
ご指摘ありがとうございます。
修正いたします。

2023-08-26 14:05 UTC, Mi462 commented on app/create/page.tsx
> +
ご指摘ありがとうございます。
コードの把握をしやすくするために、「ここからここまでは○○の部分」と分かるよう、改行しながら印をつけながら書いております。
一部修正してまた掲載します。

2023-08-26 14:18 UTC, Mi462 commented
### 実施したこと

- ファイルを.tsxから.jsxに変更
- tsconfig.jsonの削除
- onChangeの記述の削除
- 改行の修正

2023-08-27 00:58 UTC, rmrmrmrmrmrm submitted a review, later dismissed
確認しました。問題ないと思います！

2023-08-27 00:58 UTC, rmrmrmrmrmrm commented on app/page.jsx
こちら＃６と同じくです〜

2023-08-27 12:42 UTC, Mi462 commented
すみません、shinagawaさんに相談したところ、app/page.jsxのみを省くのはできないとのことなので、
app/page.jsxの内容を初期の内容に変更して差分をなくし、再びプルリクを投げてからmargeする方法を取らせてください。

お手数おかけして申し訳ありません。

2023-08-27 13:31 UTC, shtk0119 approved these changes
masudaさんに承認をもらったらマージをお願いします。

2023-09-02 11:15 UTC, rmrmrmrmrmrm commented
createページマージされてるのでクローズします

2023-09-02 11:15 UTC, closed without merging